# Generated by Django 3.1.1 on 2021-01-27 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cravings', '0004_auto_20210122_1623'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='category',
            new_name='setting',
        ),
    ]
